// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpK2q4LiRJV8BwR_X2-EdKRul2fm6eWg8',
    appId: '1:327307843268:web:347d005899207ea7815b91',
    messagingSenderId: '327307843268',
    projectId: 'aishotmaster-d6913',
    authDomain: 'aishotmaster-d6913.firebaseapp.com',
    storageBucket: 'aishotmaster-d6913.firebasestorage.app',
    measurementId: 'G-0FZPXYLECD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhEGHTAPSsc0qxRY_XukBKtIZ_IAmSY8',
    appId: '1:327307843268:android:21b29b6562fd9f4c815b91',
    messagingSenderId: '327307843268',
    projectId: 'aishotmaster-d6913',
    storageBucket: 'aishotmaster-d6913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-ec9x8MU7KIPnuRv3-L4TQD5kMMdRCc',
    appId: '1:327307843268:ios:62d7fee2cc1d3da0815b91',
    messagingSenderId: '327307843268',
    projectId: 'aishotmaster-d6913',
    storageBucket: 'aishotmaster-d6913.firebasestorage.app',
    iosBundleId: 'com.easportmaster.eaMasterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-ec9x8MU7KIPnuRv3-L4TQD5kMMdRCc',
    appId: '1:327307843268:ios:62d7fee2cc1d3da0815b91',
    messagingSenderId: '327307843268',
    projectId: 'aishotmaster-d6913',
    storageBucket: 'aishotmaster-d6913.firebasestorage.app',
    iosBundleId: 'com.easportmaster.eaMasterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpK2q4LiRJV8BwR_X2-EdKRul2fm6eWg8',
    appId: '1:327307843268:web:e3bd5cf7a274e3e8815b91',
    messagingSenderId: '327307843268',
    projectId: 'aishotmaster-d6913',
    authDomain: 'aishotmaster-d6913.firebaseapp.com',
    storageBucket: 'aishotmaster-d6913.firebasestorage.app',
    measurementId: 'G-VZ0EYFKYB3',
  );
}
